name: Deployment Workflow
on:
  push:
    branches: [ develop ]

jobs:
  jobs_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    -name: testing easyeats server ssh connection
     uses: appleboy/ssh-action@master
     with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.MY_SECRET }}
        port: 22
        script: |
          cd cd myproject
          git pull origin develop
          git status

